name: Deploy Frontend to cPanel

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Commit dist folder
        run: |
          git config --global user.email "zamirkha@gmail.com"
          git config --global user.name "MuslimRazaa"
          git add dist/ -f
          git commit -m "Auto build dist" || echo "Nothing to commit"
          git push origin main